# 애플리케이션 이름
spring.application.name=backend

# 서버 포트
server.port=8080

# MySQL 연결 정보
spring.datasource.url=jdbc:postgresql://ep-twilight-rice-aofevzw5-pooler.c-2.ap-southeast-1.aws.neon.tech/testdb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7lErPRTOXmu3
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update

# 실행 SQL 출력
spring.jpa.show-sql=true

# SQL 보기 좋게 출력
spring.jpa.properties.hibernate.format_sql=true

# 개발 편의 옵션
spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# JWT 설정
jwt.secret=bravo-unname-secret-key-must-be-at-least-32-characters
# 밀리초 단위라서 토큰 시간 설정 가능 지금은 하루로 잡아놓음 일단
# 86400000 → 24시간
# 3600000 → 1시간
# 604800000 → 7일
jwt.expiration=86400000
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

